# Main Tables
tables: "Main Tables" {
  profiles: {
    shape: sql_table
    id: uuid {constraint: primary_key}
    updated_at: timestamptz
    username: text {constraint: unique}
    first_name: text
    last_name: text
    email: text {constraint: unique}
    gender: text
    bio: text
    date_of_birth: date
    created_date: timestamptz
    last_login: timestamptz
    avatar_url: text {constraint: foreign_key}
    account_status: text
  }

  pins: {
    shape: sql_table
    pin_id: uuid {constraint: primary_key}
    places_id: text {constraint: foreign_key}
    user_id: uuid {constraint: foreign_key}
    pin_photo_url: text {constraint: foreign_key}
    pin_name: text
    address_str: text
    category: text
    lat: decimal(9,6)
    lng: decimal(9,6)
    notes: text
    created_at: timestamptz {constraint: default(now())}
    updated_at: timestamptz {constraint: default(now())}
    visited: boolean {constraint: default(false)}
    visited_at: timestamptz
    copied_from_pin_id: uuid {constraint: foreign_key}
    deviation_count: int
    review: text
    rating: int8
    review_updated_at: timestamptz
  }

  lists: {
    shape: sql_table
    list_id: uuid {constraint: primary_key}
    user_id: uuid {constraint: foreign_key}
    name: text
    description: text
    created_at: timestamptz
    updated_at: timestamptz
    private: boolean
    list_photo_url: text {constraint: foreign_key}
    followers_count: int {constraint: default(0)}
  }

  places: {
    shape: sql_table
    places_id: text {constraint: primary_key}
    name: text
    formatted_address: text
    lat: decimal(9,6)
    lng: decimal(9,6)
    types: "text[]"
    maps_url: text
    website: text
    price_level: int
    opening_hours: jsonb
    phone_number: text
    created_at: timestamptz {constraint: default(now())}
    updated_at: timestamptz {constraint: default(now())}
  }

  comments: {
    shape: sql_table
    id: uuid {constraint: primary_key}
    user_id: uuid {constraint: foreign_key}
    pin_id: uuid {constraint: foreign_key}
    comment: text
    created_at: timestamptz {constraint: default(now())}
    updated_at: timestamptz
  }

  notifications: {
    shape: sql_table
    id: uuid {constraint: primary_key}
    created_at: timestamptz
    # User to be Notified
    user_id: uuid {constraint: foreign_key}
    notification_type: text
    notification_text: text
    read: boolean {constraint: default(false)}
    read_at: timestamptz
  }

  search_history: {
    shape: sql_table
    id: uuid {constraint: primary_key}
    user_id: uuid {constraint: foreign_key}
    search_term: text
    created_at: timestamptz
  }

  pins.user_id -> profiles.id
  pins.copied_from -> pins.pin_id
  lists.user_id -> profiles.id
  comments.user_id -> profiles.id
  comments.pin_id -> pins.pin_id
  notifications.user_id -> profiles.id
  search_history.user_id -> profiles.id
  pins.places_id -> places.id
}

tables.profiles.avatar_url -> images.avatars.avatar_url
tables.pins.pin_photo_url -> images.pin_photos.pin_photo_url
tables.lists.list_photo_url -> images.list_cover_photos.list_photo_url

# Join Tables
joins: "Join Tables" {
  list_pin: {
    shape: sql_table
    id: serial {constraint: primary_key}
    dt: timestamptz {constraint: default(now())}
    list_id: uuid {constraint: foreign_key}
    pin_id: uuid {constraint: foreign_key}
  }

  bookmarks: {
    shape: sql_table
    id: int {constraint: primary_key}
    dt: timestamptz {constraint: default(now())}
    # The user who Bookmarked the Pin
    user_id: uuid {constraint: foreign_key}
    pin_id: uuid {constraint: foreign_key}
  }

  follows: {
    shape: sql_table
    id: int {constraint: primary_key}
    dt: timestamptz {constraint: default(now())}
    # User who is following the list
    user_id: uuid {constraint: foreign_key}
    list_id: uuid {constraint: foreign_key}
  }
}

joins.list_pin.list_id -> tables.lists.list_id
joins.list_pin.pin_id -> tables.pins.pin_id
joins.bookmarks.user_id -> tables.profiles.id
joins.bookmarks.pin_id -> tables.pins.pin_id
joins.follows.list_id -> tables.lists.list_id
joins.follows.user_id -> tables.profiles.id

# Image Storage Buckets
images: "Image Storage Buckets" {
  pin_photos: {
    shape: cylinder
    pin_photo_url
  }

  avatars: {
    shape: cylinder
    avatar_url
  }

  list_cover_photos: {
    shape: cylinder
    list_photo_url
  }
}

misc: "Misc Tables" {
  # Table to store Contact Submissions
  feedback: {
    shape: sql_table
    id: serial {constraint: primary_key}
    user_id: uuid {constraint: foreign_key}
    message: text,
    dt: timestamptz {constraint: default(now())}
  }
}

misc.feedback.user_id -> tables.profiles.id
